### ISSUE TITLE
Can't use 

### ISSUE THREAD

**Issue by asjkfhsakjhf** [jonathantribouharet/flutter_cast#13] opened 2021-05-28 09:05 UTC
On IOS device:
VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: OS Error: Can't assign requested address, errno = 49
#0      _NativeSocket.nativeJoinMulticast (dart:io-patch/socket_patch.dart:1560:56)
#1      _NativeSocket.joinMulticast (dart:io-patch/socket_patch.dart:1511:5)
#2      _RawDatagramSocket.joinMulticast (dart:io-patch/socket_patch.dart:2303:13)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:151:16)
<asynchronous suspension>
#4      CastDiscoveryService.search (package:cast/discovery_service.dart:21:5)
<asynchronous suspension>
#5      _CastVideoState._startSearch (package:video_test/myapp.dart:15:15)
<asynchronous suspension>

On android device：
E/Dart    (27661): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
E/Dart    (27661): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.
E/Dart    (27661): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.

**Comment by jonathantribouharet** [comment] 2021-06-14 17:38
Fixed in the last version.

**Closed by jonathantribouharet** 2021-06-14 17:38 UTC

**Comment by SirBepy** [comment] 2021-08-18 08:28
Hi! 
I am also getting this error, the problem is because of the bug I had here: https://github.com/jonathantribouharet/flutter_cast/issues/23 I had to downgrade bonsoir. But with bonsoir downgraded, I cannot take the last version of ‘cast’, rather it has to be cast: any because of the version mismatch between the newest flutter_cast version and the old bonsoir version. 

Is there any workaround that you know of? On Android it's working fine, it's only on iOS that I have this issue.
Thanks!
